import 'package:flutter/material.dart';

class AppLanguage {
  static final ValueNotifier<String> languageNotifier = ValueNotifier('English');

  static final Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'home': 'Home',
      'learn': 'Learn',
      'chat': 'Chat',
      'forum': 'Forum',
      'profile': 'Profile',
      'app_settings': 'App Settings',
      'dark_mode': 'Dark Mode',
      'language': 'App Language',
      'notifications': 'Notifications',
      'sound_effects': 'Sound Effects',
      'daily_goal': 'Daily XP Goal',
      'streak': 'Streak',
      'xp': 'XP',
      'level': 'Level',
      'daily_challenge': 'Daily Challenge',
      'weekly_activity': 'Weekly Activity',
      'welcome': 'Hello',
      'continue_learning': 'Continue Learning',
      'logout': 'Logout',
      'edit_profile': 'Edit Profile',
      'completed_lessons': 'Completed Lessons',
      'badges_achievements': 'Badges & Achievements',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'vocab_bank': 'Vocabulary Bank',
      'practice_quiz': 'Practice & Quiz',
      'forum_discussion': 'Forum Discussion',
      'live_tutor_chat': 'Live Tutor Chat',
      'weekly_engagement': 'Weekly Engagement',
      'completed': 'Completed',
      'unlock_new_achievements': 'Unlock new achievements',
      'no_announcements': 'No announcements today',
      'announcements': 'Announcements',
      'general_settings_pref': 'General settings and preferences',
      'push_notifications': 'Push Notifications',
      'send_push_updates': 'Send you push updates',
      'daily_reminder': 'Daily Reminder',
      'remind_study_daily': 'Remind you to study daily',
      'streak_alert': 'Streak Alert',
      'alert_streak_broken': 'Alert if streak is broken',
      'leaderboard_updates': 'Leaderboard Updates',
      'notify_rank_updates': 'Notify of rank updates',
      'show_chinese_chars': 'Show Chinese Characters',
      'show_chars_in_cards': 'Show characters in cards',
      'show_pinyin': 'Show Pinyin',
      'show_pronunciation_guides': 'Show pronunciation guides',
      'audio_cues_exercises': 'Audio cues during exercises',
      'reminder_time': 'Reminder Time',
      'change_app_bg': 'Change overall app background',
      'change_displayed_language': 'Change displayed language',
      'privacy_settings': 'Privacy Settings',
      'help_support': 'Help & Support',
      'version': 'Version 1.0.0',
      'logout_msg': 'Logout successful',
      'logout_confirm': 'Are you sure you want to log out?',
      'edit': 'Edit',
      'sec_notifications': 'NOTIFICATIONS',
      'sec_learning': 'LEARNING',
      'sec_teaching': 'TEACHING',
      'sec_appearance': 'APPEARANCE',
      'sec_account': 'ACCOUNT',
      'privacy_policy': 'Privacy Policy',
      'tutor_weekly_report': 'Weekly Class Report',
      'tutor_weekly_report_sub': 'Generate and show classroom metrics',
      'tutor_auto_save': 'Auto-Save Drafts',
      'tutor_auto_save_sub': 'Save lesson edits locally',
      'tutor_pinyin_creator': 'Pinyin Autocomplete',
      'tutor_pinyin_creator_sub': 'Auto-generate pinyin for characters',
      'reminder_time_sub': 'Time for daily study prompt',
      'daily_goal_sub': 'Adjust XP target of the day',
      'theme_sub': 'Switch to dark theme',
      'lang_sub': 'Change display language',
      'learning_dashboard': 'Learning Dashboard',
      'mandarin_lessons': 'Mandarin Lessons',
      'vocab_quiz_listening': 'Vocab, quiz, listening',
      'revision_tools': 'Revision tools',
      'earn_bonus_xp': 'Earn bonus XP',
      'tutor_admin_updates': 'Tutor & Admin updates',
      'starred_vocab_phrases': 'Starred Vocab & Phrases',
      'continue_lessons': 'Continue Lessons',
      'continue_lesson_btn': 'Continue Lesson',
      'course_completed': 'Course Completed',
      'my_learning_path': 'My Learning Path',
      'ready_for_practice': 'Ready for Mandarin practice?',
      'badges': 'Badges',
      'profile_student': 'Student',
      'overall_progress': 'Overall Progress',
      'progress': 'Progress',
      'leaderboard': 'Leaderboard',
      'no_lessons': 'No lessons available yet.',
      'sec_admin_settings': 'SYSTEM ADMINISTRATION',
      'admin_tutor_alerts': 'Tutor Registrations',
      'admin_tutor_alerts_sub': 'Notify when new tutor accounts sign up',
      'admin_moderation_alerts': 'Flagged Content',
      'admin_moderation_alerts_sub': 'Notify of reported forum posts or comments',
      'admin_ai_moderation': 'Automated AI Shield',
      'admin_ai_moderation_sub': 'Automatically screen and filter inappropriate content',
      'admin_maintenance_mode': 'System Maintenance',
      'admin_maintenance_mode_sub': 'Restrict student/tutor access during updates',
      'admin_developer_mode': 'Developer Console',
      'admin_developer_mode_sub': 'Enable verbose log prints and database tools',
      'admin_role': '👑 Administrator',
      'overview_panel': 'Overview Panel',
      'users_managed': 'Users Managed',
      'lessons_active': 'Lessons Active',
      'system_status': 'System Status',
      'system_management': 'System Management',
      'badge_config': 'Badge Configuration',
      'pref_theme': 'Preferences & Theme',
      'pref_theme_sub': 'Theme modes and language configurations',
      'logout_title': 'Log Out',
      'logout_sub': 'Sign out of your administrator account',
      'no_notifications_msg': 'No notifications',
      'swipe_delete_msg': 'Swipe to delete, tap to open',
      'confirm_delete_title': 'Delete Notification',
      'confirm_delete_msg': 'Are you sure you want to delete this notification?',
      'clear_all': 'Clear All',
      'target_general': 'General',
      'target_students': 'Students',
      'target_tutors': 'Tutors',
      'target_all': 'Target: All',
      'platform_announcements': 'Platform Announcements',
      'announcement_details': 'Announcement Details',
      'target_audience': 'Target Audience',
      'published_by': 'Published By',
      'published_date': 'Date & Time',
      'admin_dashboard': 'Admin Dashboard',
      'admin_overview_sub': 'Overview of MandarinMate System',
      'total_users': 'Total Users',
      'tutor_requests': 'Tutor Requests',
      'flagged_content': 'Flagged Content',
      'user_breakdown': 'System User Breakdown',
      'tutors_count': 'Tutors',
      'students_count': 'Students',
      'admins_count': 'Administrators',
      'manage_users': 'Manage Users',
      'search_users_hint': 'Search by name or email...',
      'all_roles': 'All Roles',
      'role_student': 'Student',
      'role_tutor': 'Tutor',
      'role_admin': 'Admin',
      'change_role': 'Change User Role',
      'select_role_for': 'Select new role for',
      'delete_account': 'Delete Account',
      'delete_user_confirm': 'Are you sure you want to delete this user account? This cannot be undone.',
      'manage_lessons': 'Manage Lessons',
      'create_unit_btn': '+ Create New Unit',
      'add_unit_title': 'Add Lesson Unit',
      'edit_unit_title': 'Edit Unit',
      'unit_title_label': 'Unit Title',
      'unit_desc_label': 'Unit Description (optional)',
      'delete_unit_title': 'Delete Lesson Unit',
      'delete_unit_confirm': 'Are you sure you want to delete this unit? All vocab items under it will also be deleted.',
      'manage_announcements': 'Manage Announcements',
      'audience_all': 'All',
      'audience_students': 'Students Only',
      'audience_tutors': 'Tutors Only',
      'create_announcement': 'Create Announcement',
      'edit_announcement': 'Edit Announcement',
      'announcement_title': 'Title',
      'announcement_message': 'Message Content',
      'announcement_target': 'Target Audience',
      'sys_analytics': 'System Analytics',
      'active_engagement': 'Active Engagement',
      'top_student_spotlight': 'Top Student Spotlight',
      'students_leaderboard': 'Students Leaderboard',
      'weekly_activity_logs': 'Recent Activity Logs',
      'badge_thresholds': 'Badge Unlock Thresholds',
      'badge_thresholds_desc': 'Edit the values below to adjust when badges unlock for students. Changes apply immediately.',
      'badge_xp_req': 'XP Required',
      'badge_lesson_req': 'Lessons Required',
      'badge_streak_req': 'Streak Days Required',
      'badge_level_req': 'Level Required',
      'save_all_changes': 'Save All Changes',
      'badge_save_success': 'Badge configurations saved!',
      'tutor_dashboard': 'Tutor Dashboard',
      'overview_tutor': 'Classroom Overview',
      'checklist_tutor': 'Tutor Checklist',
      'quick_links_tutor': 'System Shortcuts',
      'recent_activity_tutor': 'Recent Classroom Activities',
      'manage_vocab_units': 'Manage Vocabulary Units',
      'manage_materials': 'Manage Learning Materials',
      'manage_flashcards_set': 'Manage Flashcards',
      'manage_vocab_title': 'Vocabulary Units',
      'search_units_hint': 'Search units...',
      'ai_generate_unit': 'AI Generate Unit',
      'vocab_count': 'Vocabulary words count',
      'words_label': 'words',
      'search_materials_hint': 'Search materials...',
      'upload_material_btn': '+ Upload Material',
      'lesson_material_title': 'Lesson Materials',
      'pdf_file_label': 'PDF Document',
      'download_label': 'Downloads',
      'manage_flashcards': 'Manage Flashcards',
      'search_flashcards_hint': 'Search flashcard sets...',
      'create_set_btn': '+ Create Card Set',
      'cards_label': 'cards',
      'announcements_tutor': 'Publish Announcements',
      'search_announcements_hint': 'Search announcements...',
      'create_announcement_btn': '+ Publish Announcement',
      'system_infra': 'System Infrastructure & Security',
      'firebase_services': 'Firebase Services',
      'connected_secure': 'Connected & Secure',
      'firestore_rules': 'Firestore Database Rules',
      'enforced_v2': 'Enforced (v2)',
      'auth_validation': 'User Auth Validation',
      'utm_domain': 'UTM Email Domain Only',
      'active_status': 'Active',
      'user_dist': 'User Distribution Proportion',
      'users_nav': 'Users',
      'lessons_nav': 'Lessons',
      'analytics_nav': 'Analytics',
      'admin_shield': 'Admin Shield',
      'welcome_back': 'Welcome back, ',
      'admin_hero_desc': 'Track user growth, coordinate teaching operations, and keep content delivery sharp.',
      'status_all': 'All Status',
      'status_pending': 'Pending',
      'status_approved': 'Approved',
      'status_rejected': 'Rejected',
      'failed_load_users': 'Failed to load users.',
      'no_users_found': 'No users found.',
      'change_role_title': 'Change Role',
      'approve_member': 'Approve member',
      'reject_member': 'Reject member',
      'remove_from_list': 'Remove from list',
      'remove_confirm_title': 'Remove From List',
      'remove_confirm_desc': 'Hide this user from Manage Users? This will not delete the login account.',
      'remove_btn': 'Remove',
      'failed_load_lessons': 'Failed to load lessons.',
      'no_lessons_yet': 'No lessons yet.',
      'untitled_lesson': 'Untitled lesson',
      'add_lesson': 'Add Lesson',
      'edit_lesson': 'Edit Lesson',
      'delete_lesson': 'Delete Lesson',
      'delete_lesson_confirm': 'Delete this lesson?',
      'validation_required': 'Required',
      'label_title': 'Title',
      'label_title_chinese': 'Title Chinese',
      'label_description': 'Description',
      'label_unit_number': 'Unit Number',
      'label_total_lessons': 'Total Lessons',
      'label_xp_reward': 'XP Reward',
      'label_order': 'Order',
      'new_announcement_btn': 'New Announcement',
      'failed_load_announcements': 'Failed to load announcements.',
      'no_announcements_yet': 'No announcements yet.',
      'delete_announcement': 'Delete Announcement',
      'delete_announcement_confirm': 'Are you sure you want to delete this announcement?',
      'announcement_deleted': 'Announcement deleted successfully.',
      'failed_delete_announcement': 'Failed to delete announcement.',
      'failed_load_analytics': 'Failed to load analytics.',
      'avg_student_xp': 'Avg Student XP',
      'total_announcements': 'Total Announcements',
      'top_student_xp': 'Top Student XP',
      'top_student': 'Top Student',
      'no_student_data': 'No student data.',
      'top_5_leaderboard': 'Top 5 Student Leaderboard',
      'no_leaderboard_data': 'No leaderboard data.',
      'students_nav': 'Students',
      'all_notif_read': 'All notifications marked as read.',
      'unread': 'unread',
      'all_caught_up': 'All caught up',
      'mark_all_read': 'Mark all read',
      'no_notifications_yet': 'No Notifications Yet',
      'notify_on_updates': 'We\'ll notify you when something updates!',
      'student_no_announcements_desc': 'You will see updates from tutors and admins here.',
      'instructor': 'Instructor',
      'just_now': 'Just now',
      'read_more': 'Read more',
      'close': 'Close',
      'tutor_login_required': 'Please log in again to manage announcements.',
      'no_announcements_published': 'No announcements published yet.',
      'announcement_deleted_success': 'Announcement successfully deleted.',
      'tutor_login_manage_units': 'Please log in to manage units.',
      'no_units_created': 'No units created yet.',
      'untitled_unit': 'Untitled Unit',
      'label_created': 'Created',
      'vocabulary': 'Vocabulary',
      'update': 'Update',
      'unit_updated_success': 'Unit updated successfully.',
      'unit_deleted_success': 'Unit deleted successfully.',
      'error_deleting_unit': 'Error deleting unit',
      'ai_generate_desc': 'Let AI create vocabulary from a title',
      'tutor_login_manage_materials': 'Please log in again to manage learning materials.',
      'your_learning_materials': 'Your Learning Materials',
      'failed_load_materials': 'Failed to load your learning materials.',
      'no_materials_created': 'No learning materials created yet.',
      'label_set': 'Set',
      'materials_label': 'materials',
      'delete_materials_title': 'Delete Learning Materials',
      'delete_materials_confirm': 'Are you sure you want to delete this material?',
      'materials_deleted_success': 'Learning materials deleted successfully.',
      'failed_delete_materials': 'Failed to delete learning materials.',
      'tutor_login_manage_flashcards': 'Please log in to manage flashcards.',
      'no_flashcards_created': 'No flashcard sets created yet. Tap + to add one.',
      'untitled_level': 'Untitled Level',
      'add_new_flashcard_set': 'Add New Flashcard Set',
      'create_set_desc': 'Create a new flashcard set for a level',
      'delete_flashcard_set': 'Delete Flashcard Set',
      'delete_flashcard_set_confirm': 'Are you sure you want to delete this flashcard set? All cards inside will be deleted.',
      'flashcard_set_deleted': 'Flashcard set deleted.',
      'tutor_guide_desc': 'Ready to guide your students?',
      'tutor_hero_headline': 'Manage All Learning Resources',
      'active_students': 'active students',
      'quick_actions': 'Quick Actions',
      'view_all': 'View all',
      'tutor_action_lessons_desc': 'Manage vocab, materials, and flashcards',
      'tutor_action_students': 'Student List',
      'tutor_action_students_desc': 'View profiles and progress',
      'tutor_action_announcements_desc': 'Send updates to students',
      'tutor_action_chat_desc': 'Direct message student channels',
      'tutor_action_forum_desc': 'Discuss Mandarin topics & guide students',
      'classroom_stats_title': 'Classroom Stats • UTM Nexus',
      'server_status': 'Server Status',
      'online': 'Online',
      'firestore_db': 'Firestore DB',
      'secure': 'Secure',
      'app_version': 'App Version',
      'weekly_teaching_tasks': 'Weekly Teaching Tasks',
      'task_publish_vocab': 'Publish new vocabulary unit',
      'task_broadcast_reminder': 'Broadcast weekly test reminder',
      'task_review_forum': 'Review student forum submissions',
      'task_audit_badges': 'Audit course badges configuration',
      'lead_educator': 'Lead Educator',
      'utm_mandarin_club': 'UTM Mandarin Club',
      'teaching_overview': 'Teaching Overview',
      'students_managed': 'Students Managed',
      'lessons_published': 'Lessons Published',
      'verified_tier': 'Verified Tier',
      'senior': 'Senior',
      'classroom_info': 'Classroom Info',
      'academy': 'Academy',
      'utm_full_name': 'Universiti Teknologi Malaysia (UTM)',
      'organization': 'Organization',
      'nexus_club_name': 'Nexus Mandarin Club',
      'course_code': 'Course Code',
      'recent_activity_logs': 'Recent Activity Logs',
      'latest_broadcast_sent': 'Latest Broadcast Sent',
      'no_announcements_broadcasted': 'No announcements broadcasted',
      'tap_announcements_broadcast': 'Tap Announcements to broadcast',
      'latest_published_lesson': 'Latest Published Lesson',
      'no_lessons_published': 'No lessons published',
      'added_to_student_path': 'Added to student course path',
      'class_health_checklist': 'Class Health Checklist',
      'all_db_online': 'All classroom databases online',
      'nexus_club_active': 'Nexus Mandarin Club Active',
      'manage_lessons_hub': 'Manage Lessons Hub',
      'my_students_progress': 'My Students Progress',
      'broadcast_announcement': 'Broadcast Announcement',
      'community_forum_feed': 'Community Forum Feed',
      'announcement': 'Announcement',
      'role_updated_for': 'Role updated for',
      'approved_success': 'approved successfully.',
      'rejected_success': 'rejected successfully.',
      'removed_success': 'removed successfully.',
      'action_failed': 'Action failed',
      'tutor_admin': 'Tutor/Admin',
      'system': 'System',
      'dark_mode_enabled': 'Dark mode enabled.',
      'light_mode_enabled': 'Light mode enabled.',
      'privacy_policy_desc': 'Your privacy is our priority. In MandarinMate, we only collect essential usage statistics to optimize your learning path. We never share your credentials or speech samples with third-party service providers without your explicit consent.',
      'active_data_storage': 'Active Data Storage:',
      'privacy_data_storage': '• Firestore Database (XP progression, streaks, completed lessons)\n• Supabase Storage (Profile photos, vocabulary materials)\n• Local cache (Shared preferences toggles)',
      'support_center': 'MandarinMate Support Center',
      'support_contact_desc': 'For technical assistance, feedback, or content issues, feel free to contact us:',
      'support_contact_info': '📧 Email: support@mandarinmate.utm.my\n📍 Office: Nexus Mandarin Club, UTM Johor Bahru',
      'support_faq_title': 'Frequently Asked Questions (FAQ)',
      'support_faq_content': 'Q: How does the Daily Challenge work?\nA: Complete a short randomized quiz daily to earn extra XP and secure your learning streak!\n\nQ: How can I change my email address?\nA: Email adjustments require administrator approval. Contact support for official updates.',
      'recent_users': 'Recent Users',
      'recent_users_sub': 'Newly registered accounts',
    },
    'Bahasa Melayu': {
      'home': 'Utama',
      'learn': 'Belajar',
      'chat': 'Sembang',
      'forum': 'Forum',
      'profile': 'Profil',
      'app_settings': 'Tetapan Aplikasi',
      'dark_mode': 'Mod Gelap',
      'language': 'Bahasa Aplikasi',
      'notifications': 'Pemberitahuan',
      'sound_effects': 'Kesan Bunyi',
      'daily_goal': 'Sasaran XP Harian',
      'streak': 'Rentetan Hari',
      'xp': 'XP',
      'level': 'Tahap',
      'daily_challenge': 'Cabaran Harian',
      'weekly_activity': 'Aktiviti Mingguan',
      'welcome': 'Hai',
      'continue_learning': 'Teruskan Belajar',
      'logout': 'Log Keluar',
      'edit_profile': 'Edit Profil',
      'completed_lessons': 'Selesai Belajar',
      'badges_achievements': 'Lencana & Pencapaian',
      'save': 'Simpan',
      'cancel': 'Batal',
      'delete': 'Padam',
      'confirm': 'Sahkan',
      'vocab_bank': 'Bank Kosa Kata',
      'practice_quiz': 'Latihan & Kuiz',
      'forum_discussion': 'Perbincangan Forum',
      'live_tutor_chat': 'Sembang Tutor Langsung',
      'weekly_engagement': 'Penglibatan Mingguan',
      'completed': 'Selesai',
      'unlock_new_achievements': 'Buka pencapaian baru',
      'no_announcements': 'Tiada pengumuman hari ini',
      'announcements': 'Pengumuman',
      'general_settings_pref': 'Tetapan umum dan pilihan',
      'push_notifications': 'Pemberitahuan Tolak',
      'send_push_updates': 'Hantar kemas kini pemberitahuan',
      'daily_reminder': 'Peringatan Harian',
      'remind_study_daily': 'Peringatan untuk belajar setiap hari',
      'streak_alert': 'Amaran Rentetan',
      'alert_streak_broken': 'Amaran jika rentetan terputus',
      'leaderboard_updates': 'Kemas kini Papan Pendahulu',
      'notify_rank_updates': 'Maklumkan kemas kini kedudukan',
      'show_chinese_chars': 'Tunjuk Aksara Cina',
      'show_chars_in_cards': 'Tunjuk aksara dalam kad',
      'show_pinyin': 'Tunjuk Pinyin',
      'show_pronunciation_guides': 'Tunjuk panduan sebutan',
      'audio_cues_exercises': 'Kesan audio semasa latihan',
      'reminder_time': 'Waktu Peringatan',
      'change_app_bg': 'Tukar latar belakang keseluruhan aplikasi',
      'change_displayed_language': 'Tukar bahasa paparan',
      'privacy_settings': 'Tetapan Privasi',
      'help_support': 'Bantuan & Sokongan',
      'version': 'Versi 1.0.0',
      'logout_msg': 'Log keluar berjaya',
      'logout_confirm': 'Adakah anda pasti mahu log keluar?',
      'edit': 'Edit',
      'sec_notifications': 'PEMBERITAHUAN',
      'sec_learning': 'PEMBELAJARAN',
      'sec_teaching': 'PENGAJARAN',
      'sec_appearance': 'PENAMPILAN',
      'sec_account': 'AKAUN',
      'privacy_policy': 'Dasar Privasi',
      'tutor_weekly_report': 'Laporan Kelas Mingguan',
      'tutor_weekly_report_sub': 'Jana dan tunjuk statistik bilik darjah',
      'tutor_auto_save': 'Simpan Draf Automatik',
      'tutor_auto_save_sub': 'Simpan draf pengeditan secara tempatan',
      'tutor_pinyin_creator': 'Autolengkap Pinyin',
      'tutor_pinyin_creator_sub': 'Jana pinyin secara automatik untuk aksara',
      'reminder_time_sub': 'Waktu peringatan belajar harian',
      'daily_goal_sub': 'Tukar sasaran XP harian anda',
      'theme_sub': 'Tukar kepada tema gelap',
      'lang_sub': 'Tukar bahasa aplikasi',
      'learning_dashboard': 'Papan Pemuka Pembelajaran',
      'mandarin_lessons': 'Pelajaran Mandarin',
      'vocab_quiz_listening': 'Kosa kata, kuiz, pendengaran',
      'revision_tools': 'Alat ulang kaji',
      'earn_bonus_xp': 'Dapatkan bonus XP',
      'tutor_admin_updates': 'Kemas kini Tutor & Admin',
      'starred_vocab_phrases': 'Kosa Kata & Frasa Berbintang',
      'continue_lessons': 'Teruskan Pelajaran',
      'continue_lesson_btn': 'Teruskan Belajar',
      'course_completed': 'Kursus Selesai',
      'my_learning_path': 'Laluan Pembelajaran Saya',
      'ready_for_practice': 'Sedia untuk latihan Mandarin?',
      'badges': 'Lencana',
      'profile_student': 'Pelajar',
      'overall_progress': 'Kemajuan Keseluruhan',
      'progress': 'Kemajuan',
      'leaderboard': 'Papan Pendahulu',
      'no_lessons': 'Tiada pelajaran tersedia lagi.',
      'sec_admin_settings': 'PENTADBIRAN SISTEM',
      'admin_tutor_alerts': 'Pendaftaran Tutor',
      'admin_tutor_alerts_sub': 'Maklumkan apabila akaun tutor baharu mendaftar',
      'admin_moderation_alerts': 'Kandungan Ditandakan',
      'admin_moderation_alerts_sub': 'Maklumkan tentang siaran atau komen forum yang dilaporkan',
      'admin_ai_moderation': 'Perisai AI Automatik',
      'admin_ai_moderation_sub': 'Skrin dan tapis kandungan tidak sesuai secara automatik',
      'admin_maintenance_mode': 'Penyelenggaraan Sistem',
      'admin_maintenance_mode_sub': 'Hadkan akses pelajar/tutor semasa kemas kini',
      'admin_developer_mode': 'Konsol Pembangun',
      'admin_developer_mode_sub': 'Dayakan log terperinci dan alat pangkalan data',
      'admin_role': '👑 Pentadbir',
      'overview_panel': 'Panel Gambaran Keseluruhan',
      'users_managed': 'Pengguna Diurus',
      'lessons_active': 'Pelajaran Aktif',
      'system_status': 'Status Sistem',
      'system_management': 'Pengurusan Sistem',
      'badge_config': 'Konfigurasi Lencana',
      'pref_theme': 'Pilihan & Tema',
      'pref_theme_sub': 'Mod tema dan konfigurasi bahasa',
      'logout_title': 'Log Keluar',
      'logout_sub': 'Log keluar daripada akaun pentadbir anda',
      'no_notifications_msg': 'Tiada pemberitahuan',
      'swipe_delete_msg': 'Kuis untuk padam, ketik untuk buka',
      'confirm_delete_title': 'Padam Pemberitahuan',
      'confirm_delete_msg': 'Adakah anda pasti mahu memadam pemberitahuan ini?',
      'clear_all': 'Padam Semua',
      'target_general': 'Umum',
      'target_students': 'Pelajar',
      'target_tutors': 'Tutor',
      'target_all': 'Sasaran: Semua',
      'platform_announcements': 'Pengumuman Platform',
      'announcement_details': 'Butiran Pengumuman',
      'target_audience': 'Kumpulan Sasaran',
      'published_by': 'Diterbitkan Oleh',
      'published_date': 'Tarikh & Masa',
      'admin_dashboard': 'Papan Pemuka Pentadbir',
      'admin_overview_sub': 'Gambaran Keseluruhan Sistem MandarinMate',
      'total_users': 'Jumlah Pengguna',
      'tutor_requests': 'Permohonan Tutor',
      'flagged_content': 'Kandungan Ditandakan',
      'user_breakdown': 'Pecahan Pengguna Sistem',
      'tutors_count': 'Tutor',
      'students_count': 'Pelajar',
      'admins_count': 'Pentadbir',
      'manage_users': 'Urus Pengguna',
      'search_users_hint': 'Cari mengikut nama atau e-mel...',
      'all_roles': 'Semua Peranan',
      'role_student': 'Pelajar',
      'role_tutor': 'Tutor',
      'role_admin': 'Pentadbir',
      'change_role': 'Tukar Peranan Pengguna',
      'select_role_for': 'Pilih peranan baharu untuk',
      'delete_account': 'Padam Akaun',
      'delete_user_confirm': 'Adakah anda pasti mahu memadam akaun pengguna ini? Ini tidak boleh dikembalikan.',
      'manage_lessons': 'Urus Pelajaran',
      'create_unit_btn': '+ Bina Unit Baharu',
      'add_unit_title': 'Tambah Unit Pelajaran',
      'edit_unit_title': 'Edit Unit',
      'unit_title_label': 'Tajuk Unit',
      'unit_desc_label': 'Penerangan Unit (pilihan)',
      'delete_unit_title': 'Padam Unit Pelajaran',
      'delete_unit_confirm': 'Adakah anda pasti mahu memadam unit ini? Semua perkataan di bawahnya juga akan dipadamkan.',
      'manage_announcements': 'Urus Pengumuman',
      'audience_all': 'Semua',
      'audience_students': 'Pelajar Sahaja',
      'audience_tutors': 'Tutor Sahaja',
      'create_announcement': 'Bina Pengumuman',
      'edit_announcement': 'Edit Pengumuman',
      'announcement_title': 'Tajuk',
      'announcement_message': 'Kandungan Mesej',
      'announcement_target': 'Kumpulan Sasaran',
      'sys_analytics': 'Analisis Sistem',
      'active_engagement': 'Penglibatan Aktif',
      'top_student_spotlight': 'Tumpuan Pelajar Terbaik',
      'students_leaderboard': 'Papan Pendahulu Pelajar',
      'weekly_activity_logs': 'Log Aktiviti Terbaharu',
      'badge_thresholds': 'Had Buka Lencana',
      'badge_thresholds_desc': 'Edit nilai di bawah untuk melaraskan had lencana untuk pelajar. Perubahan berkuat kuasa serta-merta.',
      'badge_xp_req': 'XP Diperlukan',
      'badge_lesson_req': 'Pelajaran Diperlukan',
      'badge_streak_req': 'Hari Rentetan Diperlukan',
      'badge_level_req': 'Tahap Diperlukan',
      'save_all_changes': 'Simpan Semua Perubahan',
      'badge_save_success': 'Konfigurasi lencana disimpan!',
      'tutor_dashboard': 'Papan Pemuka Tutor',
      'overview_tutor': 'Gambaran Keseluruhan Kelas',
      'checklist_tutor': 'Senarai Semak Tutor',
      'quick_links_tutor': 'Pintasan Sistem',
      'recent_activity_tutor': 'Aktiviti Kelas Terbaharu',
      'manage_vocab_units': 'Urus Unit Kosa Kata',
      'manage_materials': 'Urus Bahan Pembelajaran',
      'manage_flashcards_set': 'Urus Kad Imbas',
      'manage_vocab_title': 'Unit Kosa Kata',
      'search_units_hint': 'Cari unit...',
      'ai_generate_unit': 'Jana Unit dengan AI',
      'vocab_count': 'Jumlah perkataan',
      'words_label': 'perkataan',
      'search_materials_hint': 'Cari bahan...',
      'upload_material_btn': '+ Muat Naik Bahan',
      'lesson_material_title': 'Bahan Pelajaran',
      'pdf_file_label': 'Dokumen PDF',
      'download_label': 'Muat Turun',
      'manage_flashcards': 'Urus Kad Imbas',
      'search_flashcards_hint': 'Cari set kad imbas...',
      'create_set_btn': '+ Bina Set Kad',
      'cards_label': 'kad',
      'announcements_tutor': 'Terbit Pengumuman',
      'search_announcements_hint': 'Cari pengumuman...',
      'create_announcement_btn': '+ Terbit Pengumuman',
      'system_infra': 'Infrastruktur & Keselamatan Sistem',
      'firebase_services': 'Perkhidmatan Firebase',
      'connected_secure': 'Tersambung & Selamat',
      'firestore_rules': 'Peraturan Pangkalan Data Firestore',
      'enforced_v2': 'Dikuatkuasakan (v2)',
      'auth_validation': 'Pengesahan Auth Pengguna',
      'utm_domain': 'Domain E-mel UTM Sahaja',
      'active_status': 'Aktif',
      'user_dist': 'Kadar Pecahan Pengguna',
      'users_nav': 'Pengguna',
      'lessons_nav': 'Pelajaran',
      'analytics_nav': 'Analisis',
      'admin_shield': 'Perisai Pentadbir',
      'welcome_back': 'Selamat kembali, ',
      'admin_hero_desc': 'Jejak pertumbuhan pengguna, selaraskan operasi pengajaran dan pastikan penyampaian kandungan lancar.',
      'status_all': 'Semua Status',
      'status_pending': 'Tertunda',
      'status_approved': 'Diluluskan',
      'status_rejected': 'Ditolak',
      'failed_load_users': 'Gagal memuatkan pengguna.',
      'no_users_found': 'Tiada pengguna ditemui.',
      'change_role_title': 'Tukar Peranan',
      'approve_member': 'Luluskan ahli',
      'reject_member': 'Tolak ahli',
      'remove_from_list': 'Keluarkan dari senarai',
      'remove_confirm_title': 'Keluarkan dari Senarai',
      'remove_confirm_desc': 'Sembunyikan pengguna ini daripada Urus Pengguna? Ini tidak akan memadamkan akaun log masuk.',
      'remove_btn': 'Keluarkan',
      'failed_load_lessons': 'Gagal memuatkan pelajaran.',
      'no_lessons_yet': 'Tiada pelajaran lagi.',
      'untitled_lesson': 'Pelajaran tanpa tajuk',
      'add_lesson': 'Tambah Pelajaran',
      'edit_lesson': 'Edit Pelajaran',
      'delete_lesson': 'Padam Pelajaran',
      'delete_lesson_confirm': 'Padam pelajaran ini?',
      'validation_required': 'Diperlukan',
      'label_title': 'Tajuk',
      'label_title_chinese': 'Tajuk Bahasa Cina',
      'label_description': 'Penerangan',
      'label_unit_number': 'Nombor Unit',
      'label_total_lessons': 'Jumlah Pelajaran',
      'label_xp_reward': 'Ganjaran XP',
      'label_order': 'Susunan',
      'new_announcement_btn': 'Pengumuman Baru',
      'failed_load_announcements': 'Gagal memuatkan pengumuman.',
      'no_announcements_yet': 'Tiada pengumuman lagi.',
      'delete_announcement': 'Padam Pengumuman',
      'delete_announcement_confirm': 'Adakah anda pasti mahu memadam pengumuman ini?',
      'announcement_deleted': 'Pengumuman berjaya dipadam.',
      'failed_delete_announcement': 'Gagal memadam pengumuman.',
      'failed_load_analytics': 'Gagal memuatkan analisis.',
      'avg_student_xp': 'XP Purata Pelajar',
      'total_announcements': 'Jumlah Pengumuman',
      'top_student_xp': 'XP Pelajar Terbaik',
      'top_student': 'Pelajar Terbaik',
      'no_student_data': 'Tiada data pelajar.',
      'top_5_leaderboard': 'Papan Pendahulu 5 Pelajar Terbaik',
      'no_leaderboard_data': 'Tiada data papan pendahulu.',
      'students_nav': 'Pelajar',
      'all_notif_read': 'Semua pemberitahuan ditandakan sebagai dibaca.',
      'unread': 'belum dibaca',
      'all_caught_up': 'Tiada pemberitahuan baharu',
      'mark_all_read': 'Tanda semua dibaca',
      'no_notifications_yet': 'Tiada Pemberitahuan Lagi',
      'notify_on_updates': 'Kami akan memberitahu anda apabila ada kemas kini!',
      'student_no_announcements_desc': 'Anda akan melihat kemas kini daripada tutor dan pentadbir di sini.',
      'instructor': 'Pengajar',
      'just_now': 'Baru sahaja',
      'read_more': 'Baca lagi',
      'close': 'Tutup',
      'tutor_login_required': 'Sila log masuk semula untuk mengurus pengumuman.',
      'no_announcements_published': 'Tiada pengumuman diterbitkan lagi.',
      'announcement_deleted_success': 'Pengumuman berjaya dipadam.',
      'tutor_login_manage_units': 'Sila log masuk untuk mengurus unit.',
      'no_units_created': 'Tiada unit dibina lagi.',
      'untitled_unit': 'Unit Tanpa Tajuk',
      'label_created': 'Dibina',
      'vocabulary': 'Kosa Kata',
      'update': 'Kemaskini',
      'unit_updated_success': 'Unit berjaya dikemas kini.',
      'unit_deleted_success': 'Unit berjaya dipadam.',
      'error_deleting_unit': 'Ralat memadam unit',
      'ai_generate_desc': 'Biar AI membina kosa kata daripada tajuk',
      'tutor_login_manage_materials': 'Sila log masuk semula untuk mengurus bahan pembelajaran.',
      'your_learning_materials': 'Bahan Pembelajaran Anda',
      'failed_load_materials': 'Gagal memuatkan bahan pembelajaran anda.',
      'no_materials_created': 'Tiada bahan pembelajaran dibina lagi.',
      'label_set': 'Set',
      'materials_label': 'bahan',
      'delete_materials_title': 'Padam Bahan Pembelajaran',
      'delete_materials_confirm': 'Adakah anda pasti mahu memadam bahan ini?',
      'materials_deleted_success': 'Bahan pembelajaran berjaya dipadam.',
      'failed_delete_materials': 'Gagal memadam bahan pembelajaran.',
      'tutor_login_manage_flashcards': 'Sila log masuk untuk mengurus kad imbas.',
      'no_flashcards_created': 'Tiada set kad imbas dibina lagi. Ketik + untuk menambah.',
      'untitled_level': 'Tahap Tanpa Tajuk',
      'add_new_flashcard_set': 'Bina Set Kad Imbas Baharu',
      'create_set_desc': 'Bina set kad imbas baharu untuk tahap',
      'delete_flashcard_set': 'Padam Set Kad Imbas',
      'delete_flashcard_set_confirm': 'Adakah anda pasti mahu memadam set kad imbas ini? Semua kad di dalamnya akan dipadamkan.',
      'flashcard_set_deleted': 'Set kad imbas dipadam.',
      'tutor_guide_desc': 'Sila bimbing pelajar anda.',
      'tutor_hero_headline': 'Urus Semua Sumber Pembelajaran',
      'active_students': 'pelajar aktif',
      'quick_actions': 'Tindakan Pantas',
      'view_all': 'Tunjuk semua',
      'tutor_action_lessons_desc': 'Urus kosa kata, bahan dan kad imbas',
      'tutor_action_students': 'Senarai Pelajar',
      'tutor_action_students_desc': 'Lihat profil dan kemajuan',
      'tutor_action_announcements_desc': 'Hantar kemas kini kepada pelajar',
      'tutor_action_chat_desc': 'Mesej terus saluran pelajar',
      'tutor_action_forum_desc': 'Bincang topik Mandarin & bimbing pelajar',
      'classroom_stats_title': 'Statistik Kelas • UTM Nexus',
      'server_status': 'Status Pelayan',
      'online': 'Dalam Talian',
      'firestore_db': 'Pangkalan Data Firestore',
      'secure': 'Selamat',
      'app_version': 'Versi Aplikasi',
      'weekly_teaching_tasks': 'Tugasan Pengajaran Mingguan',
      'task_publish_vocab': 'Terbit unit kosa kata baharu',
      'task_broadcast_reminder': 'Broadcast peringatan ujian mingguan',
      'task_review_forum': 'Semak penyerahan forum pelajar',
      'task_audit_badges': 'Audit konfigurasi lencana kursus',
      'lead_educator': 'Pendidik Utama',
      'utm_mandarin_club': 'Kelab Mandarin UTM',
      'teaching_overview': 'Gambaran Pengajaran',
      'students_managed': 'Pelajar Diurus',
      'lessons_published': 'Pelajaran Diterbitkan',
      'verified_tier': 'Tahap Disahkan',
      'senior': 'Kanan',
      'classroom_info': 'Maklumat Bilik Darjah',
      'academy': 'Akademi',
      'utm_full_name': 'Universiti Teknologi Malaysia (UTM)',
      'organization': 'Organisasi',
      'nexus_club_name': 'Kelab Mandarin Nexus',
      'course_code': 'Kod Kursus',
      'recent_activity_logs': 'Log Aktiviti Terbaharu',
      'latest_broadcast_sent': 'Siaran Terbaharu Dihantar',
      'no_announcements_broadcasted': 'Tiada pengumuman disiarkan',
      'tap_announcements_broadcast': 'Ketik Pengumuman untuk menyiar',
      'latest_published_lesson': 'Pelajaran Terbaharu Diterbitkan',
      'no_lessons_published': 'Tiada pelajaran diterbitkan',
      'added_to_student_path': 'Ditambah pada laluan kursus pelajar',
      'class_health_checklist': 'Senarai Semak Kesihatan Kelas',
      'all_db_online': 'Semua pangkalan data bilik darjah dalam talian',
      'nexus_club_active': 'Kelab Mandarin Nexus Aktif',
      'manage_lessons_hub': 'Hab Urus Pelajaran',
      'my_students_progress': 'Kemajuan Pelajar Saya',
      'broadcast_announcement': 'Broadcast Pengumuman',
      'community_forum_feed': 'Suapan Forum Komuniti',
      'announcement': 'Pengumuman',
      'role_updated_for': 'Peranan dikemaskini untuk',
      'approved_success': 'berjaya diluluskan.',
      'rejected_success': 'berjaya ditolak.',
      'removed_success': 'berjaya dikeluarkan.',
      'action_failed': 'Tindakan gagal',
      'tutor_admin': 'Tutor/Admin',
      'system': 'Sistem',
      'dark_mode_enabled': 'Mod gelap diaktifkan.',
      'light_mode_enabled': 'Mod cerah diaktifkan.',
      'privacy_policy_desc': 'Privasi anda adalah keutamaan kami. Di MandarinMate, kami hanya mengumpul statistik penggunaan penting untuk mengoptimumkan laluan pembelajaran anda. Kami tidak pernah berkongsi maklumat log masuk atau sampel pertuturan anda dengan pihak ketiga tanpa kebenaran anda.',
      'active_data_storage': 'Penyimpanan Data Aktif:',
      'privacy_data_storage': '• Pangkalan Data Firestore (kemajuan XP, rentetan hari, pelajaran selesai)\n• Storan Supabase (Gambar profil, bahan kosa kata)\n• Cache tempatan (Tetapan pilihan)',
      'support_center': 'Pusat Sokongan MandarinMate',
      'support_contact_desc': 'Untuk bantuan teknikal, maklum balas atau isu kandungan, sila hubungi kami:',
      'support_contact_info': '📧 E-mel: support@mandarinmate.utm.my\n📍 Pejabat: Kelab Mandarin Nexus, UTM Johor Bahru',
      'support_faq_title': 'Soalan Lazim (FAQ)',
      'support_faq_content': 'S: Bagaimana Cabaran Harian berfungsi?\nJ: Selesaikan kuiz rawak pendek setiap hari untuk mendapatkan XP tambahan dan mengekalkan rentetan belajar anda!\n\nS: Bagaimana saya boleh menukar alamat e-mel saya?\nJ: Penyesuaian e-mel memerlukan kelulusan pentadbir. Hubungi sokongan untuk kemas kini rasmi.',
      'recent_users': 'Pengguna Terkini',
      'recent_users_sub': 'Akaun yang baru didaftarkan',
    },
    '中文': {
      'home': '首页',
      'learn': '学习',
      'chat': '聊天',
      'forum': '论坛',
      'profile': '个人中心',
      'app_settings': '应用设置',
      'dark_mode': '深色模式',
      'language': '应用语言',
      'notifications': '推送通知',
      'sound_effects': '音效',
      'daily_goal': '每日 XP 目标',
      'streak': '连续天数',
      'xp': '经验值',
      'level': '等级',
      'daily_challenge': '每日挑战',
      'weekly_activity': '每周活动',
      'welcome': '你好',
      'continue_learning': '继续学习',
      'logout': '退出登录',
      'edit_profile': '编辑个人资料',
      'completed_lessons': '已完成课程',
      'badges_achievements': '徽章与成就',
      'save': '保存',
      'cancel': '取消',
      'delete': '删除',
      'confirm': '确认',
      'vocab_bank': '词汇库',
      'practice_quiz': '练习与测验',
      'forum_discussion': '论坛讨论',
      'live_tutor_chat': '在线导师交流',
      'weekly_engagement': '每周参与度',
      'completed': '已完成',
      'unlock_new_achievements': '解锁新成就',
      'no_announcements': '今天没有公告',
      'announcements': '公告',
      'general_settings_pref': '常规设置与首选项',
      'push_notifications': '推送通知',
      'send_push_updates': '向您发送推送更新',
      'daily_reminder': '每日提醒',
      'remind_study_daily': '提醒您每日学习',
      'streak_alert': '连续天数警报',
      'alert_streak_broken': '如果连续天数中断则发出警报',
      'leaderboard_updates': '排行榜更新',
      'notify_rank_updates': '通知排名更新',
      'show_chinese_chars': '显示汉字',
      'show_chars_in_cards': '在卡片中显示汉字',
      'show_pinyin': '显示拼音',
      'show_pronunciation_guides': '显示发音指南',
      'audio_cues_exercises': '练习期间的音效',
      'reminder_time': '提醒时间',
      'change_app_bg': '更改整体应用背景',
      'change_displayed_language': '更改显示的语言',
      'privacy_settings': '隐私设置',
      'help_support': '帮助与支持',
      'version': '版本 1.0.0',
      'logout_msg': '退出成功',
      'logout_confirm': '您确定要退出登录吗？',
      'edit': '编辑',
      'sec_notifications': '推送通知设置',
      'sec_learning': '学习设置',
      'sec_teaching': '教学设置',
      'sec_appearance': '外观设置',
      'sec_account': '账户管理',
      'privacy_policy': '隐私政策',
      'tutor_weekly_report': '每周班级报告',
      'tutor_weekly_report_sub': '生成并显示班级分析报告',
      'tutor_auto_save': '自动保存草稿',
      'tutor_auto_save_sub': '在本地保存课件编辑',
      'tutor_pinyin_creator': '拼音自动完成',
      'tutor_pinyin_creator_sub': '自动生成汉字的拼音',
      'reminder_time_sub': '每日学习的提醒时间',
      'daily_goal_sub': '调整今日的 XP 目标值',
      'theme_sub': '切换为深色模式',
      'lang_sub': '更改应用显示的语言',
      'learning_dashboard': '学习控制面板',
      'mandarin_lessons': '汉语课程',
      'vocab_quiz_listening': '词汇、测验与听力',
      'revision_tools': '复习工具',
      'earn_bonus_xp': '赚取额外 XP',
      'tutor_admin_updates': '教师与管理员公告',
      'starred_vocab_phrases': '已标星词句',
      'continue_lessons': '继续学习课程',
      'continue_lesson_btn': '继续学习',
      'course_completed': '课程已全部完成',
      'my_learning_path': '我的学习路径',
      'ready_for_practice': '准备好练习中文了吗？',
      'badges': '徽章',
      'profile_student': '学生',
      'overall_progress': '总体进度',
      'progress': '学习进度',
      'leaderboard': '排行榜',
      'no_lessons': '目前没有可用的课程。',
      'sec_admin_settings': '系统管理设置',
      'admin_tutor_alerts': '教师注册申请通知',
      'admin_tutor_alerts_sub': '当有新的教师账户注册时向我发送提醒',
      'admin_moderation_alerts': '违规内容检举通知',
      'admin_moderation_alerts_sub': '当论坛帖子或评论被举报时通知我',
      'admin_ai_moderation': 'AI 自动内容审查',
      'admin_ai_moderation_sub': '使用人工智能自动筛选和拦截不当内容',
      'admin_maintenance_mode': '系统维护模式',
      'admin_maintenance_mode_sub': '在更新期间限制学生与教师的访问',
      'admin_developer_mode': '开发者控制台',
      'admin_developer_mode_sub': '启用详细日志打印和数据库调试工具',
      'admin_role': '👑 管理员',
      'overview_panel': '控制面板总览',
      'users_managed': '用户管理总数',
      'lessons_active': '活跃课程总数',
      'system_status': '系统运行状态',
      'system_management': '系统管理功能',
      'badge_config': '徽章机制配置',
      'pref_theme': '个性化与主题',
      'pref_theme_sub': '深色模式与应用语言设置',
      'logout_title': '退出登录',
      'logout_sub': '安全退出当前管理员账户',
      'no_notifications_msg': '暂无通知',
      'swipe_delete_msg': '向左滑动删除，点击打开',
      'confirm_delete_title': '删除通知',
      'confirm_delete_msg': '您确定要删除此条通知吗？',
      'clear_all': '清除全部',
      'target_general': '全员通知',
      'target_students': '仅学生',
      'target_tutors': '仅教师',
      'target_all': '目标群体：所有人',
      'platform_announcements': '平台公告栏',
      'announcement_details': '公告详情',
      'target_audience': '目标群体',
      'published_by': '发布人',
      'published_date': '发布时间',
      'admin_dashboard': '管理员控制台',
      'admin_overview_sub': 'MandarinMate 系统状况总览',
      'total_users': '总用户数',
      'tutor_requests': '待审核教师申请',
      'flagged_content': '被举报违规内容',
      'user_breakdown': '系统用户角色分布',
      'tutors_count': '教师人数',
      'students_count': '学生人数',
      'admins_count': '管理员人数',
      'manage_users': '系统用户管理',
      'search_users_hint': '按姓名或电子邮箱搜索...',
      'all_roles': '所有角色',
      'role_student': '学生',
      'role_tutor': '教师',
      'role_admin': '管理员',
      'change_role': '修改用户角色',
      'select_role_for': '请为该用户分配新角色',
      'delete_account': '注销账户',
      'delete_user_confirm': '您确定要注销此用户账户吗？此操作将永久生效且不可撤销。',
      'manage_lessons': '课程大纲管理',
      'create_unit_btn': '+ 创建新教学单元',
      'add_unit_title': '添加课程单元',
      'edit_unit_title': '编辑教学单元',
      'unit_title_label': '单元名称',
      'unit_desc_label': '单元详细描述（选填）',
      'delete_unit_title': '删除教学单元',
      'delete_unit_confirm': '您确定要删除此教学单元吗？该单元下属的所有词汇库均会被同步删除。',
      'manage_announcements': '系统公告管理',
      'audience_all': '所有人',
      'audience_students': '仅限学生',
      'audience_tutors': '仅限教师',
      'create_announcement': '发布新公告',
      'edit_announcement': '编辑已有公告',
      'announcement_title': '公告标题',
      'announcement_message': '公告详细内容',
      'announcement_target': '接收目标群体',
      'sys_analytics': '系统运行数据分析',
      'active_engagement': '活跃用户参与度',
      'top_student_spotlight': '优秀学生展示墙',
      'students_leaderboard': '学生积分总排行榜',
      'weekly_activity_logs': '近期系统操作日志',
      'badge_thresholds': '徽章解锁阀值设置',
      'badge_thresholds_desc': '在此处编辑各个徽章 of 解锁条件数值，修改保存后将立即对所有学生生效。',
      'badge_xp_req': '所需经验值',
      'badge_lesson_req': '所需完成课程数',
      'badge_streak_req': '所需连续学习天数',
      'badge_level_req': '所需等级',
      'save_all_changes': '保存所有配置修改',
      'badge_save_success': '徽章解锁配置已成功保存！',
      'tutor_dashboard': '教师教学控制台',
      'overview_tutor': '班级教学状况总览',
      'checklist_tutor': '教师每日待办清单',
      'quick_links_tutor': '常用教学快捷工具',
      'recent_activity_tutor': '班级近期学习动态',
      'manage_vocab_units': '词汇教学单元管理',
      'manage_materials': '学习课件材料管理',
      'manage_flashcards_set': '记忆卡片组管理',
      'manage_vocab_title': '词汇教学单元',
      'search_units_hint': '输入关键词搜索单元...',
      'ai_generate_unit': 'AI 智能生成单元',
      'vocab_count': '所含词汇总量',
      'words_label': '个词汇',
      'search_materials_hint': '输入关键词搜索课件...',
      'upload_material_btn': '+ 上传新课件',
      'lesson_material_title': '配套课件材料',
      'pdf_file_label': 'PDF 教学文档',
      'download_label': '下载量',
      'manage_flashcards': '记忆卡片大纲管理',
      'search_flashcards_hint': '输入关键词搜索卡片组...',
      'create_set_btn': '+ 创建新卡组',
      'cards_label': '张卡片',
      'announcements_tutor': '发布班级公告',
      'search_announcements_hint': '输入关键词搜索公告...',
      'create_announcement_btn': '+ 发布新公告',
      'system_infra': '系统架构与安全防护',
      'firebase_services': 'Firebase 云服务运行状态',
      'connected_secure': '已连接并受安全保护',
      'firestore_rules': 'Firestore 数据库安全规则',
      'enforced_v2': '已强制执行 (v2)',
      'auth_validation': '用户身份登录验证限制',
      'utm_domain': '仅限 UTM 邮箱域名',
      'active_status': '正常运行',
      'user_dist': '用户角色占比分布',
      'users_nav': '用户',
      'lessons_nav': '课程',
      'analytics_nav': '数据分析',
      'admin_shield': '管理员防御盾',
      'welcome_back': '欢迎回来，',
      'admin_hero_desc': '监控用户增长，协调日常教学运营，确保课程内容优质高效递送。',
      'status_all': '所有状态',
      'status_pending': '待处理',
      'status_approved': '已批准',
      'status_rejected': '已拒绝',
      'failed_load_users': '加载用户失败。',
      'no_users_found': '未找到用户。',
      'change_role_title': '修改角色',
      'approve_member': '批准成员',
      'reject_member': '拒绝成员',
      'remove_from_list': '从列表中移除',
      'remove_confirm_title': '从列表中移除',
      'remove_confirm_desc': '从用户管理中隐藏此用户？这不会删除其登录账户。',
      'remove_btn': '移除',
      'failed_load_lessons': '加载课程失败。',
      'no_lessons_yet': '暂无课程。',
      'untitled_lesson': '未命名课程',
      'add_lesson': '添加课程',
      'edit_lesson': '编辑课程',
      'delete_lesson': '删除课程',
      'delete_lesson_confirm': '删除此课程？',
      'validation_required': '此项为必填',
      'label_title': '标题',
      'label_title_chinese': '中文标题',
      'label_description': '详细描述',
      'label_unit_number': '单元编号',
      'label_total_lessons': '课时总数',
      'label_xp_reward': '经验值奖励',
      'label_order': '排序',
      'new_announcement_btn': '新建公告',
      'failed_load_announcements': '加载公告失败。',
      'no_announcements_yet': '暂无公告。',
      'delete_announcement': '删除公告',
      'delete_announcement_confirm': '您确定要删除此公告吗？',
      'announcement_deleted': '公告已成功删除。',
      'failed_delete_announcement': '删除公告失败。',
      'failed_load_analytics': '加载分析数据失败。',
      'avg_student_xp': '学生平均经验值',
      'total_announcements': '公告总数',
      'top_student_xp': '最高学生经验值',
      'top_student': '优秀学生',
      'no_student_data': '暂无学生数据。',
      'top_5_leaderboard': '前5名学生排行榜',
      'no_leaderboard_data': '暂无排行榜数据。',
      'students_nav': '学生',
      'all_notif_read': '所有通知已标记为已读。',
      'unread': '条未读',
      'all_caught_up': '已读完所有通知',
      'mark_all_read': '全部标记已读',
      'no_notifications_yet': '暂无通知',
      'notify_on_updates': '当有更新时，我们会通知您！',
      'student_no_announcements_desc': '您将在此处看到来自教师和管理员的更新。',
      'instructor': '教员',
      'just_now': '刚刚',
      'read_more': '阅读更多',
      'close': '关闭',
      'tutor_login_required': '请重新登录以管理公告。',
      'no_announcements_published': '尚未发布任何公告。',
      'announcement_deleted_success': '公告已成功删除。',
      'tutor_login_manage_units': '请登录以管理单元。',
      'no_units_created': '尚未创建任何单元。',
      'untitled_unit': '未命名单元',
      'label_created': '创建于',
      'vocabulary': '词汇',
      'update': '更新',
      'unit_updated_success': '教学单元已成功更新。',
      'unit_deleted_success': '教学单元已成功删除。',
      'error_deleting_unit': '删除单元出错',
      'ai_generate_desc': '让 AI 根据标题自动生成词汇',
      'tutor_login_manage_materials': '请重新登录以管理课件材料。',
      'your_learning_materials': '您的课件材料',
      'failed_load_materials': '加载您的课件材料失败。',
      'no_materials_created': '尚未创建任何课件材料。',
      'label_set': '课组',
      'materials_label': '个材料',
      'delete_materials_title': '删除课件材料',
      'delete_materials_confirm': '您确定要删除此课件材料吗？',
      'materials_deleted_success': '课件材料已成功删除。',
      'failed_delete_materials': '删除课件材料失败。',
      'tutor_login_manage_flashcards': '请登录以管理记忆卡片。',
      'no_flashcards_created': '尚未创建任何卡片组。点击 + 添加。',
      'untitled_level': '未命名等级',
      'add_new_flashcard_set': '添加新记忆卡组',
      'create_set_desc': '为特定等级创建新的记忆卡组',
      'delete_flashcard_set': '删除记忆卡组',
      'delete_flashcard_set_confirm': '您确定要删除此记忆卡组吗？其中包含的所有卡片将被同步删除。',
      'flashcard_set_deleted': '记忆卡组已成功删除。',
      'tutor_guide_desc': '准备好引导您的学生了吗？',
      'tutor_hero_headline': '管理所有教学资源',
      'active_students': '名活跃学生',
      'quick_actions': '快捷操作',
      'view_all': '查看全部',
      'tutor_action_lessons_desc': '管理词汇、课件与记忆卡',
      'tutor_action_students': '学生列表',
      'tutor_action_students_desc': '查看学生个人资料与进度',
      'tutor_action_announcements_desc': '向学生发送最新通知',
      'tutor_action_chat_desc': '与学生频道直接进行私信沟通',
      'tutor_action_forum_desc': '讨论中文话题并引导学生',
      'classroom_stats_title': '班级数据统计 • UTM Nexus',
      'server_status': '服务器状态',
      'online': '在线',
      'firestore_db': 'Firestore 数据库',
      'secure': '安全保护中',
      'app_version': '应用版本',
      'weekly_teaching_tasks': '每周教学任务清单',
      'task_publish_vocab': '发布新的词汇单元',
      'task_broadcast_reminder': '广播每周测试提醒通知',
      'task_review_forum': '批阅学生论坛提交内容',
      'task_audit_badges': '核对课程徽章解锁配置',
      'lead_educator': '主讲教师',
      'utm_mandarin_club': 'UTM 华语社',
      'teaching_overview': '教学状况总览',
      'students_managed': '所辖学生总数',
      'lessons_published': '已发布课时数',
      'verified_tier': '认证教师等级',
      'senior': '高级教师',
      'classroom_info': '班级基本信息',
      'academy': '所属院校',
      'utm_full_name': '马来西亚工艺大学 (UTM)',
      'organization': '管理组织',
      'nexus_club_name': 'Nexus 华语社',
      'course_code': '课程代码',
      'recent_activity_logs': '近期教学活动日志',
      'latest_broadcast_sent': '最近一次发布公告',
      'no_announcements_broadcasted': '暂无公告发布记录',
      'tap_announcements_broadcast': '点击公告以发布新通知',
      'latest_published_lesson': '最近一次发布课程',
      'no_lessons_published': '暂无课程发布记录',
      'added_to_student_path': '已同步至学生学习路径',
      'class_health_checklist': '班级数据同步自检',
      'all_db_online': '所有班级数据库运行正常',
      'nexus_club_active': 'Nexus 华语社运行中',
      'manage_lessons_hub': '教学课件大纲中心',
      'my_students_progress': '所辖学生进度追踪',
      'broadcast_announcement': '广播班级公告',
      'community_forum_feed': '社区论坛讨论广场',
      'announcement': '公告',
      'role_updated_for': '已成功修改角色：',
      'approved_success': '已成功批准。',
      'rejected_success': '已成功拒绝。',
      'removed_success': '已成功移除。',
      'action_failed': '操作失败',
      'tutor_admin': '教师/管理员',
      'system': '系统',
      'dark_mode_enabled': '已启用深色模式。',
      'light_mode_enabled': '已启用浅色模式。',
      'privacy_policy_desc': '您的隐私是我们的首要任务。在 MandarinMate 中，我们仅收集基本的使用统计数据以优化您的学习路径。未经您的明确同意，我们绝不会与第三方服务提供商共享您的凭据或语音样本。',
      'active_data_storage': '活跃数据存储：',
      'privacy_data_storage': '• Firestore 数据库（经验值进度、连续天数、已完成课程）\n• Supabase 存储（个人资料照片、词汇材料）\n• 本地缓存（共享首选项切换）',
      'support_center': 'MandarinMate 支持中心',
      'support_contact_desc': '如有技术协助、反馈或内容问题，请随时与我们联系：',
      'support_contact_info': '📧 电子邮件：support@mandarinmate.utm.my\n📍 办公室：马来西亚工艺大学 (UTM) 新山校区 Nexus 华语社',
      'support_faq_title': '常见问题解答 (FAQ)',
      'support_faq_content': '问：每日挑战如何进行？\n答：每日完成简短的随机测验，以赚取额外经验值并保障您的学习连续天数！\n\n问：如何更改我的电子邮箱？\n答：更改邮箱需要管理员批准。请联系支持团队进行官方更新。',
      'recent_users': '最近注册用户',
      'recent_users_sub': '新注册的账户'
    }
  };

  static String translate(String key) {
    final lang = languageNotifier.value;
    return _localizedValues[lang]?[key] ?? _localizedValues['English']?[key] ?? key;
  }

  static String t(String key) => translate(key);
}
