import 'package:flutter/material.dart';

class AppLanguage {
  static final ValueNotifier<String> languageNotifier = ValueNotifier('English');

  static final Map<String, Map<String, String>> _localizedValues = {
    'English': {
      'home': 'Home',
      'learn': 'Learn',
      'chat': 'Chat',
      'forum': 'Forum',
      'profile': 'Profile',
      'app_settings': 'App Settings',
      'dark_mode': 'Dark Mode',
      'language': 'App Language',
      'notifications': 'Notifications',
      'sound_effects': 'Sound Effects',
      'daily_goal': 'Daily XP Goal',
      'streak': 'Streak',
      'xp': 'XP',
      'level': 'Level',
      'daily_challenge': 'Daily Challenge',
      'weekly_activity': 'Weekly Activity',
      'welcome': 'Hello',
      'continue_learning': 'Continue Learning',
      'logout': 'Logout',
      'edit_profile': 'Edit Profile',
      'completed_lessons': 'Completed Lessons',
      'badges_achievements': 'Badges & Achievements',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'vocab_bank': 'Vocabulary Bank',
      'practice_quiz': 'Practice & Quiz',
      'forum_discussion': 'Forum Discussion',
      'live_tutor_chat': 'Live Tutor Chat',
      'weekly_engagement': 'Weekly Engagement',
      'completed': 'Completed',
      'unlock_new_achievements': 'Unlock new achievements',
      'no_announcements': 'No announcements today',
      'announcements': 'Announcements',
      'general_settings_pref': 'General settings and preferences',
      'push_notifications': 'Push Notifications',
      'send_push_updates': 'Send you push updates',
      'daily_reminder': 'Daily Reminder',
      'remind_study_daily': 'Remind you to study daily',
      'streak_alert': 'Streak Alert',
      'alert_streak_broken': 'Alert if streak is broken',
      'leaderboard_updates': 'Leaderboard Updates',
      'notify_rank_updates': 'Notify of rank updates',
      'show_chinese_chars': 'Show Chinese Characters',
      'show_chars_in_cards': 'Show characters in cards',
      'show_pinyin': 'Show Pinyin',
      'show_pronunciation_guides': 'Show pronunciation guides',
      'audio_cues_exercises': 'Audio cues during exercises',
      'reminder_time': 'Reminder Time',
      'change_app_bg': 'Change overall app background',
      'change_displayed_language': 'Change displayed language',
      'privacy_settings': 'Privacy Settings',
      'help_support': 'Help & Support',
      'version': 'Version 1.0.0',
      'logout_msg': 'Logout successful',
      'logout_confirm': 'Are you sure you want to log out?',
      'edit': 'Edit',
      'sec_notifications': 'NOTIFICATIONS',
      'sec_learning': 'LEARNING',
      'sec_teaching': 'TEACHING',
      'sec_appearance': 'APPEARANCE',
      'sec_account': 'ACCOUNT',
      'privacy_policy': 'Privacy Policy',
      'tutor_weekly_report': 'Weekly Class Report',
      'tutor_weekly_report_sub': 'Generate and show classroom metrics',
      'tutor_auto_save': 'Auto-Save Drafts',
      'tutor_auto_save_sub': 'Save lesson edits locally',
      'tutor_pinyin_creator': 'Pinyin Autocomplete',
      'tutor_pinyin_creator_sub': 'Auto-generate pinyin for characters',
      'reminder_time_sub': 'Time for daily study prompt',
      'daily_goal_sub': 'Adjust XP target of the day',
      'theme_sub': 'Switch to dark theme',
      'lang_sub': 'Change display language',
      'learning_dashboard': 'Learning Dashboard',
      'mandarin_lessons': 'Mandarin Lessons',
      'vocab_quiz_listening': 'Vocab, quiz, listening',
      'revision_tools': 'Revision tools',
      'earn_bonus_xp': 'Earn bonus XP',
      'tutor_admin_updates': 'Tutor & Admin updates',
      'starred_vocab_phrases': 'Starred Vocab & Phrases',
      'continue_lessons': 'Continue Lessons',
      'continue_lesson_btn': 'Continue Lesson',
      'course_completed': 'Course Completed',
      'my_learning_path': 'My Learning Path',
      'ready_for_practice': 'Ready for Mandarin practice?',
      'badges': 'Badges',
      'profile_student': 'Student',
      'overall_progress': 'Overall Progress',
      'progress': 'Progress',
      'leaderboard': 'Leaderboard',
      'no_lessons': 'No lessons available yet.',
    },
    'Bahasa Melayu': {
      'home': 'Utama',
      'learn': 'Belajar',
      'chat': 'Sembang',
      'forum': 'Forum',
      'profile': 'Profil',
      'app_settings': 'Tetapan Aplikasi',
      'dark_mode': 'Mod Gelap',
      'language': 'Bahasa Aplikasi',
      'notifications': 'Pemberitahuan',
      'sound_effects': 'Kesan Bunyi',
      'daily_goal': 'Sasaran XP Harian',
      'streak': 'Rentetan Hari',
      'xp': 'XP',
      'level': 'Tahap',
      'daily_challenge': 'Cabaran Harian',
      'weekly_activity': 'Aktiviti Mingguan',
      'welcome': 'Hai',
      'continue_learning': 'Teruskan Belajar',
      'logout': 'Log Keluar',
      'edit_profile': 'Edit Profil',
      'completed_lessons': 'Selesai Belajar',
      'badges_achievements': 'Lencana & Pencapaian',
      'save': 'Simpan',
      'cancel': 'Batal',
      'delete': 'Padam',
      'confirm': 'Sahkan',
      'vocab_bank': 'Bank Kosa Kata',
      'practice_quiz': 'Latihan & Kuiz',
      'forum_discussion': 'Perbincangan Forum',
      'live_tutor_chat': 'Sembang Tutor Langsung',
      'weekly_engagement': 'Penglibatan Mingguan',
      'completed': 'Selesai',
      'unlock_new_achievements': 'Buka pencapaian baru',
      'no_announcements': 'Tiada pengumuman hari ini',
      'announcements': 'Pengumuman',
      'general_settings_pref': 'Tetapan umum dan pilihan',
      'push_notifications': 'Pemberitahuan Tolak',
      'send_push_updates': 'Hantar kemas kini pemberitahuan',
      'daily_reminder': 'Peringatan Harian',
      'remind_study_daily': 'Peringatan untuk belajar setiap hari',
      'streak_alert': 'Amaran Rentetan',
      'alert_streak_broken': 'Amaran jika rentetan terputus',
      'leaderboard_updates': 'Kemas kini Papan Pendahulu',
      'notify_rank_updates': 'Maklumkan kemas kini kedudukan',
      'show_chinese_chars': 'Tunjuk Aksara Cina',
      'show_chars_in_cards': 'Tunjuk aksara dalam kad',
      'show_pinyin': 'Tunjuk Pinyin',
      'show_pronunciation_guides': 'Tunjuk panduan sebutan',
      'audio_cues_exercises': 'Kesan audio semasa latihan',
      'reminder_time': 'Waktu Peringatan',
      'change_app_bg': 'Tukar latar belakang keseluruhan aplikasi',
      'change_displayed_language': 'Tukar bahasa paparan',
      'privacy_settings': 'Tetapan Privasi',
      'help_support': 'Bantuan & Sokongan',
      'version': 'Versi 1.0.0',
      'logout_msg': 'Log keluar berjaya',
      'logout_confirm': 'Adakah anda pasti mahu log keluar?',
      'edit': 'Edit',
      'sec_notifications': 'PEMBERITAHUAN',
      'sec_learning': 'PEMBELAJARAN',
      'sec_teaching': 'PENGAJARAN',
      'sec_appearance': 'PENAMPILAN',
      'sec_account': 'AKAUN',
      'privacy_policy': 'Dasar Privasi',
      'tutor_weekly_report': 'Laporan Kelas Mingguan',
      'tutor_weekly_report_sub': 'Jana dan tunjuk statistik bilik darjah',
      'tutor_auto_save': 'Simpan Draf Automatik',
      'tutor_auto_save_sub': 'Simpan draf pengeditan secara tempatan',
      'tutor_pinyin_creator': 'Autolengkap Pinyin',
      'tutor_pinyin_creator_sub': 'Jana pinyin secara automatik untuk aksara',
      'reminder_time_sub': 'Waktu peringatan belajar harian',
      'daily_goal_sub': 'Tukar sasaran XP harian anda',
      'theme_sub': 'Tukar kepada tema gelap',
      'lang_sub': 'Tukar bahasa aplikasi',
      'learning_dashboard': 'Papan Pemuka Pembelajaran',
      'mandarin_lessons': 'Pelajaran Mandarin',
      'vocab_quiz_listening': 'Kosa kata, kuiz, pendengaran',
      'revision_tools': 'Alat ulang kaji',
      'earn_bonus_xp': 'Dapatkan bonus XP',
      'tutor_admin_updates': 'Kemas kini Tutor & Admin',
      'starred_vocab_phrases': 'Kosa Kata & Frasa Berbintang',
      'continue_lessons': 'Teruskan Pelajaran',
      'continue_lesson_btn': 'Teruskan Belajar',
      'course_completed': 'Kursus Selesai',
      'my_learning_path': 'Laluan Pembelajaran Saya',
      'ready_for_practice': 'Sedia untuk latihan Mandarin?',
      'badges': 'Lencana',
      'profile_student': 'Pelajar',
      'overall_progress': 'Kemajuan Keseluruhan',
      'progress': 'Kemajuan',
      'leaderboard': 'Papan Pendahulu',
      'no_lessons': 'Tiada pelajaran tersedia lagi.',
    },
    '中文': {
      'home': '首页',
      'learn': '学习',
      'chat': '聊天',
      'forum': '论坛',
      'profile': '个人中心',
      'app_settings': '应用设置',
      'dark_mode': '深色模式',
      'language': '应用语言',
      'notifications': '推送通知',
      'sound_effects': '音效',
      'daily_goal': '每日 XP 目标',
      'streak': '连续天数',
      'xp': '经验值',
      'level': '等级',
      'daily_challenge': '每日挑战',
      'weekly_activity': '每周活动',
      'welcome': '你好',
      'continue_learning': '继续学习',
      'logout': '退出登录',
      'edit_profile': '编辑个人资料',
      'completed_lessons': '已完成课程',
      'badges_achievements': '徽章与成就',
      'save': '保存',
      'cancel': '取消',
      'delete': '删除',
      'confirm': '确认',
      'vocab_bank': '词汇库',
      'practice_quiz': '练习与测验',
      'forum_discussion': '论坛讨论',
      'live_tutor_chat': '在线导师交流',
      'weekly_engagement': '每周参与度',
      'completed': '已完成',
      'unlock_new_achievements': '解锁新成就',
      'no_announcements': '今天没有公告',
      'announcements': '公告',
      'general_settings_pref': '常规设置与首选项',
      'push_notifications': '推送通知',
      'send_push_updates': '向您发送推送更新',
      'daily_reminder': '每日提醒',
      'remind_study_daily': '提醒您每日学习',
      'streak_alert': '连续天数警报',
      'alert_streak_broken': '如果连续天数中断则发出警报',
      'leaderboard_updates': '排行榜更新',
      'notify_rank_updates': '通知排名更新',
      'show_chinese_chars': '显示汉字',
      'show_chars_in_cards': '在卡片中显示汉字',
      'show_pinyin': '显示拼音',
      'show_pronunciation_guides': '显示发音指南',
      'audio_cues_exercises': '练习期间的音效',
      'reminder_time': '提醒时间',
      'change_app_bg': '更改整体应用背景',
      'change_displayed_language': '更改显示的语言',
      'privacy_settings': '隐私设置',
      'help_support': '帮助与支持',
      'version': '版本 1.0.0',
      'logout_msg': '退出成功',
      'logout_confirm': '您确定要退出登录吗？',
      'edit': '编辑',
      'sec_notifications': '推送通知设置',
      'sec_learning': '学习设置',
      'sec_teaching': '教学设置',
      'sec_appearance': '外观设置',
      'sec_account': '账户管理',
      'privacy_policy': '隐私政策',
      'tutor_weekly_report': '每周班级报告',
      'tutor_weekly_report_sub': '生成并显示班级分析报告',
      'tutor_auto_save': '自动保存草稿',
      'tutor_auto_save_sub': '在本地保存课件编辑',
      'tutor_pinyin_creator': '拼音自动完成',
      'tutor_pinyin_creator_sub': '自动生成汉字的拼音',
      'reminder_time_sub': '每日学习的提醒时间',
      'daily_goal_sub': '调整今日的 XP 目标值',
      'theme_sub': '切换为深色模式',
      'lang_sub': '更改应用显示的语言',
      'learning_dashboard': '学习控制面板',
      'mandarin_lessons': '汉语课程',
      'vocab_quiz_listening': '词汇、测验与听力',
      'revision_tools': '复习工具',
      'earn_bonus_xp': '赚取额外 XP',
      'tutor_admin_updates': '教师与管理员公告',
      'starred_vocab_phrases': '已标星词句',
      'continue_lessons': '继续学习课程',
      'continue_lesson_btn': '继续学习',
      'course_completed': '课程已全部完成',
      'my_learning_path': '我的学习路径',
      'ready_for_practice': '准备好练习中文了吗？',
      'badges': '徽章',
      'profile_student': '学生',
      'overall_progress': '总体进度',
      'progress': '学习进度',
      'leaderboard': '排行榜',
      'no_lessons': '目前没有可用的课程。',
    }
  };

  static String translate(String key) {
    final lang = languageNotifier.value;
    return _localizedValues[lang]?[key] ?? _localizedValues['English']?[key] ?? key;
  }

  static String t(String key) => translate(key);
}
