// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwGbcS7Hsf0Y9IG8EvKx5gIRMNs7Zb5Uw',
    appId: '1:253053635674:web:887caf9668f06b5caf5c63',
    messagingSenderId: '253053635674',
    projectId: 'mandarinmate-utm',
    authDomain: 'mandarinmate-utm.firebaseapp.com',
    storageBucket: 'mandarinmate-utm.firebasestorage.app',
    measurementId: 'G-QH0SDJY7EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjTpnMxYIT-z850Z2ecOggoZuSUkyu2ow',
    appId: '1:253053635674:android:944bb7b4ba0df1f0af5c63',
    messagingSenderId: '253053635674',
    projectId: 'mandarinmate-utm',
    storageBucket: 'mandarinmate-utm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxAmfRx-yKYq4LWUpSJ9kDQIrRqn_fo38',
    appId: '1:253053635674:ios:e72bf08d74a32061af5c63',
    messagingSenderId: '253053635674',
    projectId: 'mandarinmate-utm',
    storageBucket: 'mandarinmate-utm.firebasestorage.app',
    iosClientId: '253053635674-egafsn0s38fsose01hjls7o914cf7d95.apps.googleusercontent.com',
    iosBundleId: 'com.example.mandarinmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxAmfRx-yKYq4LWUpSJ9kDQIrRqn_fo38',
    appId: '1:253053635674:ios:e72bf08d74a32061af5c63',
    messagingSenderId: '253053635674',
    projectId: 'mandarinmate-utm',
    storageBucket: 'mandarinmate-utm.firebasestorage.app',
    iosClientId: '253053635674-egafsn0s38fsose01hjls7o914cf7d95.apps.googleusercontent.com',
    iosBundleId: 'com.example.mandarinmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwGbcS7Hsf0Y9IG8EvKx5gIRMNs7Zb5Uw',
    appId: '1:253053635674:web:718bc8c3103e6135af5c63',
    messagingSenderId: '253053635674',
    projectId: 'mandarinmate-utm',
    authDomain: 'mandarinmate-utm.firebaseapp.com',
    storageBucket: 'mandarinmate-utm.firebasestorage.app',
    measurementId: 'G-LJ1F0GMV19',
  );
}
